repository: francolmenar/francolmenar.github.io

layout: sidebar
style: light
show_hire: "false" # To Display the Available for hire or not, even if you are not in a company
show_projects: "false"
show_tech: "true"
show_organizations: "true"
show_topics: "true"


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: francisco-manuel-colmenar-lamas-91b924160
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  # CSS: "true"
  # Cryptocurrency: "true"
  Flutter: "true"
  # Monero: "true"
  # Security: "true"
  Rust: "true"
  Zcash: "true"

organizations:
  Personal Projects: "true"
  UC3M: "true"
  UT: "true"
  USYD: "true"
  VUW: "true"

technologies:
  # Bitcoin: "true"
  C: "true"
  # CSS: "true"
  Docker: "true"
  # Ethereum: "true"
  Firebase: "true"
  # HTML: "true"
  Java: "true"
  # JavaScript: "true"
  Jupyter Notebook: "true"
  # Monero: "true"
  Python: "true"
  React: "true"
  Rust: "true"
  SQL: "true"